Repository love-work-club/README, pull requests merged in 2022-12, with the labels that each got.

#6 [Feature] atoms 버튼 스타일 적용 및 Theme, GlobalStyle 파일 작성
  package-lock.json
  package.json
  src/App.js
  src/commons/style/GlobalStyle.js
  src/commons/style/themes/default.js
  src/components/atoms/Button/Button.js
  src/index.js
Labels: feature

#5 [회원가입/프로필설정] component 구성 완료
  package-lock.json
  src/.DS_Store
  src/App.js
  src/assets/profileImg.png
  src/assets/uploadBtn.png
  src/commons/style/GlobalStyle.jsx
  src/pages/.DS_Store
  src/pages/Join/.DS_Store
  src/pages/Join/ButtonStyle.jsx
  src/pages/Join/FormStyle.jsx
  src/pages/Join/InputStyle.jsx
  src/pages/Join/Join.js
  src/pages/Join/JoinMembership.jsx
  src/pages/Join/ProfileSetting.jsx
  src/pages/Join/TitleTextStyle.jsx
Labels: feature

#7 [Feature] EmailLogin 화면 html / css 리액트 컴포넌트 구현
  .prettierrc.json
  README.md
  package-lock.json
  src/pages/Login/EmailLogin.jsx
  src/pages/Login/emailLogin.js
  src/pages/Login/styled.jsx
Labels: feature

#10 [Design] 로그인 하단 부분 여백 좁혀 수정
  src/pages/Login/Login.js
Labels: feature

#14 [Modify] ProfileSetting - README 시작하기 button 공통 comp 변경 / 사진선택 이미지 수정
  src/pages/Join/ButtonStyle.jsx
  src/pages/Join/ProfileSetting.jsx
Labels: feature

#8 [Add] images initial setting
  src/assets/icons/feed-comment.png
  src/assets/icons/feed-comment.svg
  src/assets/icons/feed-like.png
  src/assets/icons/feed-like.svg
  src/assets/icons/feed-list-on.png
  src/assets/icons/feed-list-on.svg
  src/assets/icons/feed-list.png
  src/assets/icons/feed-list.svg
  src/assets/icons/feed-more-option.png
  src/assets/icons/feed-more-option.svg
  src/assets/icons/feed-photo-on.png
  src/assets/icons/feed-photo-on.svg
  src/assets/icons/feed-photo.png
  src/assets/icons/feed-photo.svg
  src/assets/icons/feed-upload-photo.png
  src/assets/icons/feed-upload-photo.svg
  src/assets/icons/icon-back.png
  src/assets/icons/icon-back.svg
  src/assets/icons/icon-search.png
  src/assets/icons/icon-search.svg
  src/assets/icons/nav-chatting-on.png
  src/assets/icons/nav-chatting-on.svg
  src/assets/icons/nav-chatting.png
  src/assets/icons/nav-chatting.svg
  src/assets/icons/nav-home-on.png
  src/assets/icons/nav-home-on.svg
  src/assets/icons/nav-home.png
  src/assets/icons/nav-home.svg
  src/assets/icons/nav-profile-on.png
  src/assets/icons/nav-profile-on.svg
  src/assets/icons/nav-profile.png
  src/assets/icons/nav-profile.svg
  src/assets/icons/nav-upload-on.png
  src/assets/icons/nav-upload-on.svg
  src/assets/icons/nav-upload.png
  src/assets/icons/nav-upload.svg
  src/assets/icons/profile-photo.png
  src/assets/icons/profile-photo.svg
  src/assets/icons/profile-share.png
  src/assets/icons/profile-share.svg
  src/assets/icons/sns-facebook.png
  src/assets/icons/sns-facebook.svg
  src/assets/icons/sns-google.png
  src/assets/icons/sns-google.svg
  src/assets/icons/sns-kakao.png
  src/assets/icons/sns-kakao.svg
Labels: feature

#18 Feature/atoms inputlabel
  .gitignore
  src/components/atoms/Input/Input.jsx
  src/components/atoms/Input/style.jsx
  src/components/atoms/Label/Label.jsx
  src/components/atoms/Label/style.jsx
  src/components/molecules/LabeledInput/LabeledInput.js
  src/components/molecules/LabeledInput/style.jsx
Labels: feature

#20 [Feat] Top NavBar 컴포넌트별 마크업 및 스타일 구현
  src/components/molecules/TopNavBar/TopNavBar.jsx
Labels: feature

#25 [Feat] organisms-yourprofile 마크업 및 스타일 컴포넌트 구현 / icon 폴더 내 svg 파일 추가
  src/assets/icons/message-btn.svg
  src/assets/icons/share-btn.svg
  src/components/organisms/YourProfile/ButtonGroup.jsx
  src/components/organisms/YourProfile/FollowCount.jsx
  src/components/organisms/YourProfile/ProfileDsc.jsx
  src/components/organisms/YourProfile/ProfileImg.jsx
  src/components/organisms/YourProfile/YourProfile.jsx
Labels: feature

#30 Feature/user list
  src/assets/user_list_default_profile.png
  src/components/atoms/Button/Button.js
  src/components/atoms/UserList/UserList.jsx
Labels: feature

#39 molecules 컴포넌트 구성 및 아이콘 추가 라우터 초기 구현
  src/App.js
  src/assets/icons/icon-heart.svg
  src/assets/icons/message-circle.svg
  src/assets/icons/profile_big.svg
  src/assets/icons/profile_sm.svg
  src/assets/logo/404.png
  src/assets/logo/readme.png
  src/assets/logo/splash.png
  src/commons/style/GlobalStyle.jsx
  src/commons/style/themes/default.js
  src/components/molecules/Comment/CommentBar.js
  src/components/molecules/Posts/Posts.js
  src/components/molecules/ProductItem/ProductItem.js
  src/pages/Chat/Chat.js
  src/pages/Home/Home.js
  src/pages/Splash/Splash.js
Labels: feature

#47 Feature/yourprofile
  src/App.js
  src/components/atoms/BottomNavBarWrap/BottomNavBarWrap.jsx
  src/components/atoms/Chat/Chat.jsx
  src/components/atoms/FeedList/FeedList.jsx
  src/components/atoms/FeedPhoto/FeedPhoto.jsx
  src/components/atoms/Home/Home.jsx
  src/components/atoms/Profile/Profile.jsx
  src/components/atoms/Upload/Upload.jsx
  src/components/molecules/BottomNavBarBasic/BottomNavBarBasic.jsx
  src/components/molecules/ProductItem/ProductItem.js
  src/components/molecules/TopNavBarView/TopNavBarView.jsx
  src/components/organisms/YourProfile/ButtonGroupMy.jsx
  src/components/organisms/YourProfile/ButtonGroupYour.jsx
  src/components/organisms/YourProfile/ProfileMyOrg.jsx
  src/components/organisms/YourProfile/ProfileYourOrg.jsx
  src/pages/Profile/Empty.jsx
  src/pages/Profile/OnSale.jsx
  src/pages/Profile/PostImg.jsx
  src/pages/Profile/PostList.jsx
  src/pages/Profile/YourProfile.jsx
Labels: feature

#44 [Feat] MyProfile 페이지 마크업 및 스타일
  src/pages/ModifyProfile/ModifyProfile.jsx
Labels: design

#48 [Feat]채팅 리스트 마크업 및 스타일
  src/pages/Chat/ChatList.jsx
Labels: design

#62 [Feat] 로그인 로직 구현 및 유효성 검사 추가
  package-lock.json
  src/pages/Join/JoinMembership.jsx
  src/pages/Login/styled.jsx
Labels: feature

#56 [Design] 채팅 리스트 프로필 이미지 svg파일로 수정
  src/pages/Chat/ChatList.jsx
Labels: design

#58 [Feat] Feature/register join 프로필 셋팅 기능 구현
  src/pages/Join/InputStyle.jsx
  src/pages/Join/JoinMembership.jsx
  src/pages/Join/ProfileSetting.jsx
Labels: feature

#64 [Add] 라우터 기능 추가 구현
  src/App.js
  src/index.js
  src/pages/Pages.js
  src/pages/Splash/Splash.js
  src/store/auth-context.js
Labels: feature

#70 [Add] 채팅 페이지의 이미지 업로드 아이콘 추가
  src/assets/images/chat-upload-photo.svg
Labels: Add

#72 [Modify] import 파일 위치 주소 변경
  src/pages/EmailLogin/EmailLogin.jsx
Labels: Modify

#76 [Add] Search User 페이지 라우터 추가
  src/pages/Pages.js
Labels: Add

#73 [Feature]Home feed 구현
  src/assets/icons/feed-more-option.svg
  src/components/atoms/TopNavBarWrap/TopNavBarWrap.jsx
  src/components/molecules/Posts/Posts.js
  src/components/molecules/TopNavBarFeedSearch/TopNavBarFeedSearch.jsx
  src/components/organisms/InitHomeFeed/InitHomeFeed.js
  src/pages/Home/Home.js
Labels: API, Feature, Design

#74 [Feat] 채팅룸 마크업 및 스타일
  src/components/molecules/TopNavBarFeedTitle/TopNavBarFeedTitle.jsx
  src/pages/Chat/ChatRoom.jsx
Labels: Feature, Design

#80 [Feat] gitignore 추가
  .gitignore
Labels: Setting

#81 Feature/search 유저 검색 결과 리스트 화면에 렌더링
  .env
  src/components/atoms/TopNavBarWrap/TopNavBarWrap.jsx
  src/components/molecules/SearchUserList/SearchUserList.jsx
  src/components/molecules/SearchUserList/SearchUserListStyle.jsx
  src/components/molecules/SearchUserListItem/SearchUserListItem.jsx
  src/components/molecules/TopNavBarFeedSearch/TopNavBarFeedSearch.jsx
  src/components/molecules/TopNavBarUserSearch/TopNavBarUserSearch.jsx
  src/components/molecules/TopNavBarUserSearch/TopNavBarUserSearchStyle.jsx
  src/components/organisms/SearchUser/SearchUser.jsx
  src/pages/Search/Search.jsx
Labels: Feature

#82 하단 네브바 기능 구현
  src/commons/style/GlobalStyle.jsx
  src/commons/style/themes/default.js
  src/components/molecules/BottomNavBarBasic/BottomNavBarBasic.jsx
Labels: Feature, Design

#85 [Style] 상단 내비바 색상 보완
  src/components/atoms/TopNavBarWrap/TopNavBarWrap.jsx
  src/components/molecules/SearchUserList/SearchUserListStyle.jsx
Labels: Html & css, Design

#87 [Feat]Postdetail페이지 구현 및 댓글 기능 추가
  src/components/molecules/Comment/CommentBar.js
  src/components/molecules/Comment/CommentList.js
  src/components/molecules/Posts/Posts.js
  src/hooks/use-api.js
  src/pages/DetailPosts/DetailPosts.js
  src/pages/Home/Home.js
  src/pages/NotFound/NotFound.js
Labels: API, Feature

#89 [Feat] 뒤로가기 기능 구현
  src/components/atoms/BackBtn/BackBtn.jsx
  src/components/molecules/TopNavBarFeedSearch/TopNavBarFeedSearch.jsx
Labels: Feature

#90 [Modify] console.log 제거
  src/components/organisms/SearchUser/SearchUser.jsx
Labels: Modify

#92 이메일로 회원가입 페이지 수정사항
  src/pages/Join/FormStyle.jsx
  src/pages/Join/JoinMembership.jsx
  src/pages/Pages.js
Labels: BugFix, Html & css, Modify
