Repository love-work-club/README, pull requests merged in 2023-01, with the labels that each got.

#93 [Feat] 상품등록 페이지 마크업 완료
  src/pages/AddProduct/AddProduct.jsx
  src/pages/Pages.js
Labels: Feature, Design

#94 Feature/myprofile
  src/App.js
  src/components/atoms/Button/Button.js
  src/components/atoms/UserList/UserList.jsx
  src/components/atoms/UserListItem/UserListItem.jsx
  src/components/molecules/BottomNavBarBasic/BottomNavBarBasic.jsx
  src/components/molecules/ButtonGroupMy/ButtonGroupMy.jsx
  src/components/molecules/ButtonGroupYour/ButtonGroupYour.jsx
  src/components/molecules/FollowCount/FollowCount.jsx
  src/components/molecules/ProfileDsc/ProfileDsc.jsx
  src/components/molecules/TopNavBarFollow/TopNavBarFollow.jsx
  src/components/molecules/TopNavBarView/TopNavBarView.jsx
  src/components/organisms/PostList/PostList.jsx
  src/components/organisms/Profile/MyProfile/ProfileMyOrg.jsx
  src/components/organisms/Profile/YourProfile/ProfileYourOrg.jsx
  src/components/organisms/Sale/OnSale.jsx
  src/pages/EmailLogin/EmailLogin.jsx
  src/pages/Followers/Followers.jsx
  src/pages/Followings/Followings.jsx
  src/pages/Pages.js
  src/pages/Profile/MyProfile/MyProfile.jsx
  src/pages/Profile/YourProfile/YourProfile.jsx
  src/store/auth-context.js
Labels: Feature

#96 회원가입 페이지 밸리데이션 추가 및 레이아웃 스타일 수정
  src/pages/Join/JoinMembership.jsx
Labels: Html & css, Modify

#102 [Feat]Upload
  src/assets/icons/icon-heart-fill.svg
  src/commons/style/GlobalStyle.jsx
  src/components/atoms/PostModal/PostModal.jsx
  src/components/atoms/UserListItem/UserListItem.jsx
  src/components/molecules/Posts/Posts.js
  src/components/molecules/SearchUserList/SearchUserList.jsx
  src/components/molecules/SearchUserListItem/SearchUserListItem.jsx
  src/components/molecules/TopNavBarSave/TopNavBarSave.jsx
  src/components/organisms/PostList/PostList.jsx
  src/components/organisms/Profile/MyProfile/ProfileMyOrg.jsx
  src/components/organisms/Profile/YourProfile/ProfileYourOrg.jsx
  src/components/organisms/Sale/OnSale.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/DetailPosts/DetailPosts.js
  src/pages/Home/Home.js
  src/pages/Pages.js
  src/pages/Upload/Upload.js
Labels: BugFix, Refactor, API, Feature, Modify, Add

#98 Feature/bottomnavbar
  src/commons/style/GlobalStyle.jsx
  src/components/atoms/BottomNavBarItem/BottomNavBarItem.jsx
  src/components/atoms/BottomNavBarWrap/BottomNavBarWrap.jsx
  src/components/molecules/BottomNavBarBasic/BottomNavBarBasic.jsx
  src/pages/Chat/ChatList.jsx
  src/pages/EmailLogin/EmailLogin.jsx
  src/pages/Home/Home.js
  src/pages/Profile/MyProfile/MyProfile.jsx
Labels: Add

#107 Splash logo UI 작업
  src/assets/images/searchBg.png
  src/assets/images/searchBg.svg
  src/assets/logo/README_splash_logo.svg
  src/components/organisms/InitHomeFeed/InitHomeFeed.js
  src/pages/Splash/Splash.js
  src/pages/Splash/Splash.jsx
Labels: Html & css, Add, Design

#110 Feature/topnavbar modify
  src/components/atoms/BottomNavBarWrap/BottomNavBarWrap.jsx
  src/components/atoms/TopNavBarWrap/TopNavBarWrap.jsx
  src/components/organisms/Profile/MyProfile/ProfileMyOrg.jsx
  src/components/organisms/Profile/YourProfile/ProfileYourOrg.jsx
Labels: Design

#112 Feature/link modifyprofile
  src/components/molecules/ButtonGroupMy/ButtonGroupMy.jsx
  src/components/organisms/Profile/MyProfile/ProfileMyOrg.jsx
  src/components/organisms/Profile/YourProfile/ProfileYourOrg.jsx
Labels: Feature

#113 Feature/myprofile remove
  src/components/molecules/ButtonGroupMy/ButtonGroupMy.jsx
  src/components/organisms/Profile/MyProfile/ProfileMyOrg.js
Labels: Modify
